prefix              = "dev"
location            = "centralindia"
resource_group_name = "dev-governance-rg"
subscription_id     = "7e43e805-0130-426e-935b-5380e24fa05b"
storage_account_name = "devtfstateudk"
container_name       = "dev-tfstate-container"